name: Projektarbeit_Neutronenradiographie
channels:
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - blas=1.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2022.9.14
  - certifi=2022.9.14
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.4
  - cryptography=36.0.0
  - et_xmlfile=1.1.0
  - flask=2.0.2
  - idna=3.3
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - itsdangerous=2.1.2
  - jinja2=3.0.2
  - libiconv=1.16
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.12
  - lxml=4.9.1
  - markupsafe=2.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.12.0
  - msoffcrypto-tool=5.0.1
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.3.5
  - parameterized=0.8.1
  - pip=21.2.2
  - pluggy=0.13.1
  - py=1.10.0
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytest=6.2.4
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - pywin32=303
  - requests=2.27.1
  - retrying=1.3.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - suds-jurko=0.6
  - tbb=2021.5.0
  - toml=0.10.2
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.1.2
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xlrd=2.0.1
  - xz=5.2.5
  - zlib=1.2.12